"""Add email verification fields to User model

Revision ID: ed4af5548d60
Revises: ae2116c6ffb9
Create Date: 2025-12-24 21:20:41.914502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed4af5548d60'
down_revision: Union[str, None] = 'ae2116c6ffb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with nullable=True first for existing rows
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('code_expires_at', sa.DateTime(timezone=True), nullable=True))
    
    # Set default value for existing users (mark them as verified to not break existing accounts)
    op.execute("UPDATE users SET is_verified = true WHERE is_verified IS NULL")
    
    # Now make is_verified NOT NULL
    op.alter_column('users', 'is_verified', nullable=False, server_default=sa.false())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'code_expires_at')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
